on:
  push:
    branches:
      - main
  pull_request:

name: Test

jobs:
  # NOTE: Tests run via `pre-commit` on 3.11; All other versions of Python run just the tests.
  pre-commit:
      name: Run pre-commit on 3.11
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        - uses: ./.github/actions/setup-env
          with:
            python-version: "3.11"
        # Executes `pre-commit` with the `make` directive to ensure all dependencies are found
        - run: |
            source $CONDA/bin/activate
            conda activate anaconda-packaging-utils
            make pre-commit
  test:
      runs-on: ubuntu-latest
      name: Test on ${{ matrix.python-version }}
      strategy:
        matrix:
          python-version: ["3.11"] # TODO: Bump this to 3.12 when supported and drop 3.11 (covered in pre-commit)
      steps:
        - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        - uses: ./.github/actions/setup-env
          with:
            python-version: ${{ matrix.python-version }}
        - run: |
            source $CONDA/bin/activate
            conda activate anaconda-packaging-utils
            make test
  build-recipe:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
          with:
            repository: AnacondaRecipes/anaconda-packaging-utils-feedstock
            path: ./feedstock
        - name: Cache conda env
          id: cache-conda
          uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
          env:
            cache-name: conda-env-cache
          with:
            path: '/usr/share/miniconda/envs'
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Build package
          run: |
            cp -r ./feedstock/abs.yaml ./feedstock/recipe .
            source $CONDA/bin/activate
            conda install conda-build
            conda-build -c distro-tooling .
